name: district_rate_hash_map_tree
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  google_maps_flutter:
    git:
      url: https://github.com/kolmakovruslan/plugins.git
      path: packages/google_maps_flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true